/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-primary": "#232829",
        "bg-secondary": "#313637",
        "bg-tertiary": "#2D3233",
        accent: "#FDB056",
        "accent-green": "#81FE95",
        "text-primary": "#FFFFFF",
        "text-secondary": "#DCDCDC",
        "text-gray": "#CDCDCD",
        "text-muted": "#9B9B9B",
        "text-old-price": "#919191",
        "sale-red": "#FD5656",
        "offer-green": "#1D5B43",
        "star-yellow": "#FFBB00",
        "star-red": "#FF4E4E",
      },
      fontFamily: {
        montserrat: ["Montserrat", "sans-serif"],
        raleway: ["Raleway", "sans-serif"],
        gilroy: ["Gilroy", "sans-serif"],
        "pt-root": ["PT Root UI", "sans-serif"],
      },
      fontSize: {
        xs: "10px",
        sm: "12px",
        base: "14px",
        lg: "16px",
        xl: "18px",
        "2xl": "20px",
        "3xl": "22px",
        "4xl": "24px",
        "5xl": "26px",
        "6xl": "28px",
        "7xl": "30px",
        "8xl": "32px",
        "9xl": "34px",
        "10xl": "40px",
        "11xl": "50px",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "16px",
        xl: "18px",
        "2xl": "20px",
        "3xl": "30px",
        "4xl": "34px",
        "5xl": "40px",
        "6xl": "60px",
      },
    },
  },
  plugins: [],
};
